/**
 * Write the film's <audio> elements into index.html.
 *
 * WHY THIS IS A SCRIPT AND NOT HAND-TYPED MARKUP. There are eighty-three cues
 * plus the bed. HyperFrames finds media with a flat document query, so every
 * one has to exist in the markup before any script runs — building them in the
 * composition's own <script> would be too late. Generating them keeps
 * tools/cues.mjs the single source of truth for the mix, exactly as
 * engine/src/EngineSound.tsx was in the Remotion cut.
 *
 * It is idempotent: it replaces whatever sits between the two markers, so it
 * can be re-run after any edit to the cue table.
 *
 *   node tools/gen-audio.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CUES } from './cues.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'index.html');

const FPS = 30;
const f = (n) => Number((n / FPS).toFixed(7));

const START = '<!--HF_AUDIO-->';
const END = '<!--/HF_AUDIO-->';

const lines = [];
lines.push(START);
lines.push('      <!--');
lines.push('        SOUND. Generated by tools/gen-audio.mjs from tools/cues.mjs.');
lines.push('        Do not hand-edit between these two markers.');
lines.push('');
lines.push('        THE BED is assets/audio/bed-48.mp3 — the Mixkit tech-house groove');
lines.push('        time-stretched from 124.5 BPM to 120 with ffmpeg atempo, then built');
lines.push('        from itself: its first 30.0s (fifteen bars) followed by its own first');
lines.push('        18.0s (nine bars), with a 15ms fade across the seam. Both sides of the');
lines.push('        joint are downbeats, so the loop sits on the grid (DO-NOT-DO 48, 66).');
lines.push('');
lines.push(`        ${CUES.length} cues. Levels are set on the timeline, in the sound block.`);
lines.push('      -->');
lines.push(
  `      <audio id="bed" src="assets/audio/bed-48.mp3" data-start="0" data-duration="48" data-track-index="20" data-volume="0"></audio>`,
);

CUES.forEach((cue, i) => {
  const note = String(cue.note).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
  lines.push(
    `      <audio id="cue${i}" src="assets/audio/sfx/${cue.src}.mp3"` +
      ` data-start="${f(cue.from)}" data-duration="${f(cue.frames)}"` +
      ` data-track-index="${21 + (i % 8)}" data-volume="0"` +
      ` data-note="${note}"></audio>`,
  );
});

lines.push('      <script>');
lines.push('        /* The cue table, for the level tweens further down the page. */');
lines.push(
  '        window.__HF_CUES = ' +
    JSON.stringify(
      CUES.map((c) => ({
        from: c.from,
        frames: c.frames,
        volume: c.volume,
        ...(c.swell ? { swell: c.swell } : {}),
      })),
    ) +
    ';',
);
lines.push('      <\/script>');
lines.push(`      ${END}`);

const block = lines.join('\n');

let html = readFileSync(target, 'utf8');
const startAt = html.indexOf(START);
if (startAt === -1) throw new Error('index.html has no ' + START + ' marker');
const endAt = html.indexOf(END);
const tail = endAt === -1 ? startAt + START.length : endAt + END.length;

html = html.slice(0, startAt) + block + html.slice(tail);
writeFileSync(target, html);

console.log(`Wrote ${CUES.length} cues + 1 bed into index.html`);
