/**
 * Write the film's <audio> elements into index.html.
 *
 * WHY THIS IS A SCRIPT AND NOT HAND-TYPED MARKUP. There are eighty-odd cues plus
 * the bed. HyperFrames finds media with a flat document query, so every element
 * has to exist in the markup before any script runs — building them in the
 * composition's own <script> would be too late. Generating them keeps
 * tools/cues.mjs the single source of truth for the mix.
 *
 * It is idempotent: it replaces whatever sits between the two markers, so it can
 * be re-run after any edit to the cue table.
 *
 *   node tools/gen-audio.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CUES } from './cues.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const target = join(root, 'index.html');

const FPS = 30;
const f = (n) => Number((n / FPS).toFixed(7));

/* A cue pointing at a file that is not on disk renders as silence and nothing
   warns you. Fail loudly instead. */
const missing = CUES.map((c) => c.src).filter(
  (s, i, a) => a.indexOf(s) === i && !existsSync(join(root, 'assets', 'audio', 'sfx', s + '.mp3')),
);
if (missing.length) {
  throw new Error('cue files not on disk:\n  ' + missing.join('\n  '));
}

/* Clamp every cue to the real length of its file.
 *
 * A slot longer than the media is silently shortened at render time, so the
 * four-frame tail fade this film writes for every cue would be tweening a
 * volume on a clip that had already stopped — which is how a cue ends up
 * clicking instead of fading. Measure the file; never trust the table.
 */
const seconds = (rel) => {
  const out = execFileSync(
    'ffprobe',
    ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0',
     join(root, 'assets', 'audio', 'sfx', rel + '.mp3')],
    { encoding: 'utf8' },
  );
  return Number(String(out).trim());
};

const lengths = new Map();
let clamped = 0;
for (const cue of CUES) {
  if (!lengths.has(cue.src)) lengths.set(cue.src, seconds(cue.src));
  const max = Math.floor(lengths.get(cue.src) * FPS);
  if (cue.frames > max) {
    cue.frames = max;
    clamped++;
  }
}

const START = '<!--HF_AUDIO-->';
const END = '<!--/HF_AUDIO-->';

const lines = [];
lines.push(START);
lines.push('      <!--');
lines.push('        SOUND. Generated by tools/gen-audio.mjs from tools/cues.mjs.');
lines.push('        Do not hand-edit between these two markers.');
lines.push('');
lines.push('        THE BED is assets/audio/bed-48.mp3 — the Mixkit tech-house groove,');
lines.push('        time-stretched from 124.5 BPM to 120 with ffmpeg atempo (which does');
lines.push('        not shift pitch) and rebuilt to 48.0s as its own first 30.0s, fifteen');
lines.push('        bars, followed by its own first 18.0s, nine bars, with a 15ms fade');
lines.push('        across the seam. Both sides of the joint are downbeats, so the loop');
lines.push('        sits ON the grid rather than merely near it (DO-NOT-DO 48, 66).');
lines.push('');
lines.push(`        ${CUES.length} cues. Levels are set on the timeline, in the sound block.`);
lines.push('      -->');
lines.push(
  '      <audio id="bed" src="assets/audio/bed-48.mp3" data-start="0" data-duration="48"' +
    ' data-track-index="20" data-volume="0"></audio>',
);

CUES.forEach((cue, i) => {
  const note = String(cue.note)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/"/g, '&quot;');
  lines.push(
    `      <audio id="cue${i}" src="assets/audio/sfx/${cue.src}.mp3"` +
      ` data-start="${f(cue.from)}" data-duration="${f(cue.frames)}"` +
      ` data-track-index="${21 + (i % 8)}" data-volume="0"` +
      ` data-note="${note}"></audio>`,
  );
});

lines.push('      <script>');
lines.push('        /* The cue table, for the level tweens in the composition script. */');
lines.push(
  '        window.__HF_CUES = ' +
    JSON.stringify(
      CUES.map((c) => ({
        from: c.from,
        frames: c.frames,
        volume: c.volume,
        ...(c.swell ? { swell: c.swell } : {}),
      })),
    ) +
    ';',
);
lines.push('      <\/script>');
lines.push(`      ${END}`);

const block = lines.join('\n');

let html = readFileSync(target, 'utf8');
const startAt = html.indexOf(START);
if (startAt === -1) throw new Error('index.html has no ' + START + ' marker');
const endAt = html.indexOf(END);
const tail = endAt === -1 ? startAt + START.length : endAt + END.length;

html = html.slice(0, startAt) + block + html.slice(tail);
writeFileSync(target, html);

console.log(`Wrote ${CUES.length} cues + 1 bed into index.html (${clamped} clamped to their file length)`);
